USE [master]
GO
USE QLBongDa
GO
-- Cau e
IF OBJECT_ID('dbo.SP_SEL_NO_ENCRYPT','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SP_SEL_NO_ENCRYPT')
GO
CREATE PROCEDURE SP_SEL_NO_ENCRYPT (@TenCLB nvarchar(100), @TenQG nvarchar(60))
AS
BEGIN
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, ct.VITRI
	FROM CAUTHU as CT
	INNER JOIN CAULACBO as CLB ON CT.MACLB = CLB.MACLB
	INNER JOIN QUOCGIA as QG ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG;
END;
GO
-- Cau f
IF OBJECT_ID('dbo.SP_SEL_ENCRYPT','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SP_SEL_ENCRYPT')
GO
CREATE PROCEDURE SP_SEL_ENCRYPT (@TenCLB nvarchar(100), @TenQG nvarchar(60))
WITH ENCRYPTION
AS
BEGIN
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, ct.VITRI
	FROM CAUTHU as CT
	INNER JOIN CAULACBO as CLB ON CT.MACLB = CLB.MACLB
	INNER JOIN QUOCGIA as QG ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG;
END;
GO
-- cau g
EXEC SP_SEL_NO_ENCRYPT N'SHB Đà Nẵng', N'Brazil' 
EXEC SP_SEL_ENCRYPT N'SHB Đà Nẵng', N'Brazil'
GO
-- Kiem tra ma hoa hay chua
SELECT object_definition(object_id) AS [Proc Definition]
FROM sys.objects 
WHERE type='P'
GO

-- cau j
-- procedure 1
IF OBJECT_ID('dbo.SP_SEL_ENCRYPT','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SP_SEL_ENCRYPT')
GO
CREATE PROCEDURE SPCau1 (@TenCLB nvarchar(100), @TenQG nvarchar(60))
AS
BEGIN
	SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, ct.VITRI
	FROM CAUTHU as CT
	INNER JOIN CAULACBO as CLB ON CT.MACLB = CLB.MACLB
	INNER JOIN QUOCGIA as QG ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG;
END;
GO
--EXEC SPCau1 N'SHB Đà Nẵng', N'Brazil' 
GO
-- procedure 2
IF OBJECT_ID('dbo.SPCau2','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau2')
GO
CREATE PROCEDURE SPCau2 (@Vong int, @Nam int)
AS
BEGIN
	SELECT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
	FROM TRANDAU as TD
	INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
	INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
	INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
	WHERE TD.VONG = @Vong AND TD.NAM = @Nam;
END;
GO
--EXEC SPCau2 3, 2009
GO
-- procedure 3
IF OBJECT_ID('dbo.SPCau3','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau3')
GO
CREATE PROCEDURE SPCau3 (@TenQG nvarchar(60))
AS
BEGIN
	SELECT HLV.MAHLV, HLV.TENHLV,HLV.NGAYSINH,HLV.DIACHI,HCLB.VAITRO,CLB.TENCLB
	FROM HUANLUYENVIEN as HLV
	INNER JOIN HLV_CLB as HCLB ON HLV.MAHLV = HCLB.MAHLV
	INNER JOIN CAULACBO as CLB ON HCLB.MACLB = CLB.MACLB
	INNER JOIN QUOCGIA as QG ON HLV.MAQG = QG.MAQG
	WHERE QG.TENQG = @TenQG;
END;
GO
--EXEC SPCau3 N'Việt Nam'
GO
-- procedure 4
IF OBJECT_ID('dbo.SPCau4','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau4')
GO
CREATE PROCEDURE SPCau4 (@TenQG nvarchar(60))
AS
BEGIN 
	SELECT CLB4.MACLB, CLB4.TENCLB, S4.TENSAN, T4.TENTINH, COUNT(CT4.MACT)
	FROM CAULACBO AS CLB4
	INNER JOIN SANVD AS S4 ON S4.MASAN = CLB4.MASAN
	INNER JOIN TINH AS T4 ON T4.MATINH = CLB4.MATINH
	INNER JOIN CAUTHU AS CT4 ON CT4.MACLB = CLB4.MACLB
	WHERE not EXISTS
		(SELECT CT41.MACT
		FROM CAUTHU AS CT41, CAULACBO AS CLB41, QUOCGIA AS QG41	
		WHERE CT41.MACLB = CLB41.MACLB AND CLB41.MACLB = CLB4.MACLB AND CT41.MAQG = QG41.MAQG AND QG41.TENQG = N'Việt Nam')
	Group by CLB4.MACLB, CLB4.TENCLB, S4.TENSAN, T4.TENTINH
	Having count(ct4.mact) > 2
end;
go

--EXEC SPCau4 N'Việt Nam'
GO	

-- procedure 5
IF OBJECT_ID('dbo.SPCau5','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau5')
GO
CREATE PROCEDURE SPCau5 (@TenQG nvarchar(60))
AS
BEGIN 
	SELECT T5.TENTINH, COUNT(*)
	FROM CAULACBO AS CLB5
	INNER JOIN CAUTHU AS CT5 ON CT5.MACLB = CLB5.MACLB
	INNER JOIN TINH AS T5 ON T5.MATINH = CLB5.MATINH
	WHERE 
		CT5.VITRI = N'Tiền đạo'
	GROUP BY T5.TENTINH
END;
GO

--EXEC SPCau5 N'Việt Nam'
go
-- procedure 6
IF OBJECT_ID('dbo.SPCau6','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau6')
GO
CREATE PROCEDURE SPCau6 (@Vong int, @Nam int)
AS
BEGIN
	SELECT CLB6.TENCLB, T6.TENTINH
	FROM CAULACBO AS CLB6
	INNER JOIN TINH AS T6 ON T6.MATINH = CLB6.MATINH
	INNER JOIN BANGXH AS BXH6 ON BXH6.MACLB = CLB6.MACLB
	WHERE 
		BXH6.VONG = @Vong AND BXH6.NAM = @Nam AND BXH6.HANG = 1
END;
GO

--EXEC SPCau6 3,2009
GO

-- procedure 7
IF OBJECT_ID('dbo.SPCau7','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau7')
GO
CREATE PROCEDURE SPCau7 (@DienThoai nvarchar(20),@VaiTro nvarchar(100))
AS
BEGIN
	SELECT HLV.TENHLV
	FROM HUANLUYENVIEN AS HLV
	INNER JOIN HLV_CLB AS HCLB ON HLV.MAHLV = HCLB.MAHLV
	WHERE HLV.DIENTHOAI = @DienThoai AND HCLB.VAITRO = @VaiTro;
END;
GO
--EXEC SPCau7 @DienThoai = NULL, @VaiTro =N'HLV Chính'
--EXEC SPCau7 @DienThoai = NULL, @VaiTro =N'HLV Thủ môn'
GO
-- procedure 8
IF OBJECT_ID('dbo.SPCau8','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau8')
GO
CREATE PROCEDURE SPCau8 (@QuocGia nvarchar(20),@VaiTro nvarchar(100))
AS
BEGIN
	SELECT HLV.MAHLV, HLV.TENHLV
	FROM HUANLUYENVIEN AS HLV 
	INNER JOIN HLV_CLB AS HCLB ON HLV.MAHLV = HCLB.MAHLV
	WHERE HLV.MAQG = @QuocGia AND HCLB.VAITRO IS NOT NULL;
END;
GO
EXEC SPCau8 @QuocGia = N'VN', @VaiTro = NULL

-- procedure 9
IF OBJECT_ID('dbo.SPCau9','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau9')
GO
CREATE PROCEDURE SPCau9 (@Vong int, @Nam int, @Hang int)
AS
BEGIN
	SELECT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
	FROM TRANDAU as TD
	INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
	INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
	INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
	INNER JOIN BANGXH as BXH on TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB 
	WHERE TD.VONG = @Vong AND  BXH.HANG = @Hang AND TD.NAM = @Nam;
END;
GO
--EXEC SPCau2 3, 2009, 1
GO
-- procedure 10

IF OBJECT_ID('dbo.SPCau10','P') IS NOT NULL 
    EXEC('DROP PROCEDURE SPCau10')
GO
CREATE PROCEDURE SPCau10 (@Vong int, @Nam int, @Hang int)
AS
BEGIN
	SELECT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
	FROM TRANDAU as TD
	INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
	INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
	INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
	INNER JOIN BANGXH as BXH on TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB 
	WHERE TD.VONG = @Vong AND  BXH.HANG = @Hang AND TD.NAM = @Nam;
END;
GO
--EXEC SPCau2 3, 2009, 5
GO
