USE [master]
GO
USE QLBongDa
GO
-- cau i
-- view 1
IF OBJECT_ID('dbo.vCau1','V') IS NOT NULL 
    EXEC('DROP VIEW vCau1')
GO
CREATE VIEW vCau1 AS
SELECT CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, ct.VITRI
FROM CAUTHU as CT
INNER JOIN CAULACBO as CLB ON CT.MACLB = CLB.MACLB
INNER JOIN QUOCGIA as QG ON CT.MAQG = QG.MAQG
WHERE CLB.TENCLB = N'SHB Đà Nẵng' AND QG.TENQG = N'Brazil';
GO
--SELECT * FROM vCau1
GO
-- view 2
IF OBJECT_ID('dbo.vCau2','V') IS NOT NULL 
        EXEC('DROP VIEW vCau2');
GO
CREATE VIEW vCau2 AS
SELECT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU as TD
INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
WHERE TD.VONG = 3 AND TD.NAM = 2009;
GO
--SELECT * FROM vCau2
GO
-- view 3
IF OBJECT_ID('dbo.vCau3','V') IS NOT NULL 
        EXEC('DROP VIEW vCau3');
GO
CREATE VIEW vCau3 AS
SELECT HLV.MAHLV, HLV.TENHLV,HLV.NGAYSINH,HLV.DIACHI,HCLB.VAITRO,CLB.TENCLB
FROM HUANLUYENVIEN as HLV
INNER JOIN HLV_CLB as HCLB ON HLV.MAHLV = HCLB.MAHLV
INNER JOIN CAULACBO as CLB ON HCLB.MACLB = CLB.MACLB
INNER JOIN QUOCGIA as QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam';
GO
--SELECT * FROM vCau3
GO
-- view 4
IF OBJECT_ID('dbo.vCau4','V') IS NOT NULL 
        EXEC('DROP VIEW vCau4');
GO
CREATE VIEW vCau4 AS
SELECT CLB4.MACLB, CLB4.TENCLB, S4.TENSAN, T4.TENTINH, COUNT(CT4.MACT) AS CAUTHUNGOAIQUOC
	FROM CAULACBO AS CLB4
	INNER JOIN SANVD AS S4 ON S4.MASAN = CLB4.MASAN
	INNER JOIN TINH AS T4 ON T4.MATINH = CLB4.MATINH
	INNER JOIN CAUTHU AS CT4 ON CT4.MACLB = CLB4.MACLB
	WHERE not EXISTS
		(SELECT CT41.MACT
		FROM CAUTHU AS CT41, CAULACBO AS CLB41, QUOCGIA AS QG41	
		WHERE CT41.MACLB = CLB41.MACLB AND CLB41.MACLB = CLB4.MACLB AND CT41.MAQG = QG41.MAQG AND QG41.TENQG = N'Việt Nam')
	Group by CLB4.MACLB, CLB4.TENCLB, S4.TENSAN, T4.TENTINH
	Having count(ct4.mact) > 2
GO
--SELECT * FROM vCau4
GO
-- view 5
IF OBJECT_ID('dbo.vCau5','V') IS NOT NULL 
        EXEC('DROP VIEW vCau5');
GO
CREATE VIEW vCau5 AS
SELECT T5.TENTINH, COUNT(*) AS SOLUONGTIENDAO
	FROM CAULACBO AS CLB5
	INNER JOIN CAUTHU AS CT5 ON CT5.MACLB = CLB5.MACLB
	INNER JOIN TINH AS T5 ON T5.MATINH = CLB5.MATINH
	WHERE 
		CT5.VITRI = N'Tiền đạo'
	GROUP BY T5.TENTINH
GO

--SELECT *FROM vCau5
GO
-- view 6
IF OBJECT_ID('dbo.vCau6','V') IS NOT NULL 
        EXEC('DROP VIEW vCau6');
GO
CREATE VIEW vCau6 AS
SELECT CLB6.TENCLB, T6.TENTINH
	FROM CAULACBO AS CLB6
	INNER JOIN TINH AS T6 ON T6.MATINH = CLB6.MATINH
	INNER JOIN BANGXH AS BXH6 ON BXH6.MACLB = CLB6.MACLB
	WHERE 
		BXH6.VONG = 3 AND BXH6.NAM = 2009 AND BXH6.HANG = 1
GO
--SELECT *FROM vCau6
GO
-- view 7
IF OBJECT_ID('dbo.vCau7','V') IS NOT NULL 
        EXEC('DROP VIEW vCau7');
GO
CREATE VIEW vCau7 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN AS HLV
INNER JOIN HLV_CLB AS HCLB ON HLV.MAHLV = HCLB.MAHLV
WHERE HLV.DIENTHOAI = NULL AND HCLB.VAITRO IS NOT NULL;
GO
--SELECT*  FROM vCau7
GO
-- view 8
IF OBJECT_ID('dbo.vCau8','V') IS NOT NULL 
        EXEC('DROP VIEW vCau8');
GO
CREATE VIEW vCau8 AS
SELECT HLV.MAHLV, HLV.TENHLV
FROM HUANLUYENVIEN AS HLV 
INNER JOIN HLV_CLB AS HCLB ON HLV.MAHLV = HCLB.MAHLV
WHERE HLV.MAQG = N'VN' AND HCLB.VAITRO = NULL;
GO

--SELECT * FROM vCau8
-- view 9
IF OBJECT_ID('dbo.vCau9','V') IS NOT NULL 
        EXEC('DROP VIEW vCau9');
GO
CREATE VIEW vCau9 AS
SELECT DISTINCT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU as TD
INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
INNER JOIN BANGXH as BXH on TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB 
WHERE TD.VONG <= 3 AND  BXH.HANG = 1 AND TD.NAM = 2009;
GO 

-- view 10
IF OBJECT_ID('dbo.vCau10','V') IS NOT NULL 
        EXEC('DROP VIEW vCau10');
GO
CREATE VIEW vCau10 AS
SELECT DISTINCT TD.MATRAN, TD.NGAYTD,SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU as TD
INNER JOIN CAULACBO as CLB1 ON TD.MACLB1 = CLB1.MACLB
INNER JOIN CAULACBO as CLB2 ON TD.MACLB2 = CLB2.MACLB
INNER JOIN SANVD as SVD ON TD.MASAN = SVD.MASAN
INNER JOIN BANGXH as BXH on TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB 
WHERE TD.VONG <= 3 AND  BXH.HANG = 5 AND TD.NAM = 2009;
GO 